sudo: true
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6
services:
  - redis-server
language: ruby
rvm:
  - '2.3'
env:
  - SUITE=python
  - SUITE=ruby
before_install:
  - bin/before-install
script:
  - bin/test
